export interface Country {
  alpha2: string
  alpha3: string
  name: string
  countryCallingCodes: string[]
}

export const countries: Country[] = [
  {
    alpha2: 'US',
    alpha3: 'USA',
    name: 'United States',
    countryCallingCodes: ['+1'],
  },
]

export const allCountries: Country[] = [
  {
    alpha2: 'US',
    alpha3: 'USA',
    name: 'United States',
    countryCallingCodes: ['+1'],
  },
  {
    alpha2: 'CA',
    alpha3: 'CAN',
    name: 'Canada',
    countryCallingCodes: ['+1'],
  },
  {
    alpha2: 'GB',
    alpha3: 'GBR',
    name: 'United Kingdom',
    countryCallingCodes: ['+44'],
  },
  {
    alpha2: 'AU',
    alpha3: 'AUS',
    name: 'Australia',
    countryCallingCodes: ['+61'],
  },
  {
    alpha2: 'DE',
    alpha3: 'DEU',
    name: 'Germany',
    countryCallingCodes: ['+49'],
  },
  {
    alpha2: 'FR',
    alpha3: 'FRA',
    name: 'France',
    countryCallingCodes: ['+33'],
  },
  {
    alpha2: 'JP',
    alpha3: 'JPN',
    name: 'Japan',
    countryCallingCodes: ['+81'],
  },
  {
    alpha2: 'CN',
    alpha3: 'CHN',
    name: 'China',
    countryCallingCodes: ['+86'],
  },
  {
    alpha2: 'IN',
    alpha3: 'IND',
    name: 'India',
    countryCallingCodes: ['+91'],
  },
  {
    alpha2: 'BR',
    alpha3: 'BRA',
    name: 'Brazil',
    countryCallingCodes: ['+55'],
  },
  {
    alpha2: 'RU',
    alpha3: 'RUS',
    name: 'Russia',
    countryCallingCodes: ['+7'],
  },
  {
    alpha2: 'MX',
    alpha3: 'MEX',
    name: 'Mexico',
    countryCallingCodes: ['+52'],
  },
  {
    alpha2: 'IT',
    alpha3: 'ITA',
    name: 'Italy',
    countryCallingCodes: ['+39'],
  },
  {
    alpha2: 'ES',
    alpha3: 'ESP',
    name: 'Spain',
    countryCallingCodes: ['+34'],
  },
  {
    alpha2: 'KR',
    alpha3: 'KOR',
    name: 'South Korea',
    countryCallingCodes: ['+82'],
  },
  {
    alpha2: 'ZA',
    alpha3: 'ZAF',
    name: 'South Africa',
    countryCallingCodes: ['+27'],
  },
  {
    alpha2: 'SG',
    alpha3: 'SGP',
    name: 'Singapore',
    countryCallingCodes: ['+65'],
  },
  {
    alpha2: 'NZ',
    alpha3: 'NZL',
    name: 'New Zealand',
    countryCallingCodes: ['+64'],
  },
  {
    alpha2: 'SE',
    alpha3: 'SWE',
    name: 'Sweden',
    countryCallingCodes: ['+46'],
  },
  {
    alpha2: 'NO',
    alpha3: 'NOR',
    name: 'Norway',
    countryCallingCodes: ['+47'],
  },
  {
    alpha2: 'DK',
    alpha3: 'DNK',
    name: 'Denmark',
    countryCallingCodes: ['+45'],
  },
  {
    alpha2: 'FI',
    alpha3: 'FIN',
    name: 'Finland',
    countryCallingCodes: ['+358'],
  },
  {
    alpha2: 'NL',
    alpha3: 'NLD',
    name: 'Netherlands',
    countryCallingCodes: ['+31'],
  },
  {
    alpha2: 'BE',
    alpha3: 'BEL',
    name: 'Belgium',
    countryCallingCodes: ['+32'],
  },
  {
    alpha2: 'CH',
    alpha3: 'CHE',
    name: 'Switzerland',
    countryCallingCodes: ['+41'],
  },
  {
    alpha2: 'AT',
    alpha3: 'AUT',
    name: 'Austria',
    countryCallingCodes: ['+43'],
  },
  {
    alpha2: 'PT',
    alpha3: 'PRT',
    name: 'Portugal',
    countryCallingCodes: ['+351'],
  },
  {
    alpha2: 'GR',
    alpha3: 'GRC',
    name: 'Greece',
    countryCallingCodes: ['+30'],
  },
  {
    alpha2: 'IE',
    alpha3: 'IRL',
    name: 'Ireland',
    countryCallingCodes: ['+353'],
  },
  {
    alpha2: 'PL',
    alpha3: 'POL',
    name: 'Poland',
    countryCallingCodes: ['+48'],
  },
  {
    alpha2: 'TR',
    alpha3: 'TUR',
    name: 'Turkey',
    countryCallingCodes: ['+90'],
  },
  {
    alpha2: 'AE',
    alpha3: 'ARE',
    name: 'United Arab Emirates',
    countryCallingCodes: ['+971'],
  },
  {
    alpha2: 'SA',
    alpha3: 'SAU',
    name: 'Saudi Arabia',
    countryCallingCodes: ['+966'],
  },
  {
    alpha2: 'IL',
    alpha3: 'ISR',
    name: 'Israel',
    countryCallingCodes: ['+972'],
  },
  {
    alpha2: 'EG',
    alpha3: 'EGY',
    name: 'Egypt',
    countryCallingCodes: ['+20'],
  },
  {
    alpha2: 'TH',
    alpha3: 'THA',
    name: 'Thailand',
    countryCallingCodes: ['+66'],
  },
  {
    alpha2: 'MY',
    alpha3: 'MYS',
    name: 'Malaysia',
    countryCallingCodes: ['+60'],
  },
  {
    alpha2: 'ID',
    alpha3: 'IDN',
    name: 'Indonesia',
    countryCallingCodes: ['+62'],
  },
  {
    alpha2: 'PH',
    alpha3: 'PHL',
    name: 'Philippines',
    countryCallingCodes: ['+63'],
  },
  {
    alpha2: 'VN',
    alpha3: 'VNM',
    name: 'Vietnam',
    countryCallingCodes: ['+84'],
  },
  {
    alpha2: 'AR',
    alpha3: 'ARG',
    name: 'Argentina',
    countryCallingCodes: ['+54'],
  },
  {
    alpha2: 'CL',
    alpha3: 'CHL',
    name: 'Chile',
    countryCallingCodes: ['+56'],
  },
  {
    alpha2: 'CO',
    alpha3: 'COL',
    name: 'Colombia',
    countryCallingCodes: ['+57'],
  },
  {
    alpha2: 'PE',
    alpha3: 'PER',
    name: 'Peru',
    countryCallingCodes: ['+51'],
  },
  {
    alpha2: 'VE',
    alpha3: 'VEN',
    name: 'Venezuela',
    countryCallingCodes: ['+58'],
  },
  {
    alpha2: 'MA',
    alpha3: 'MAR',
    name: 'Morocco',
    countryCallingCodes: ['+212'],
  },
  {
    alpha2: 'NG',
    alpha3: 'NGA',
    name: 'Nigeria',
    countryCallingCodes: ['+234'],
  },
  {
    alpha2: 'KE',
    alpha3: 'KEN',
    name: 'Kenya',
    countryCallingCodes: ['+254'],
  },
  {
    alpha2: 'GH',
    alpha3: 'GHA',
    name: 'Ghana',
    countryCallingCodes: ['+233'],
  },
  {
    alpha2: 'TZ',
    alpha3: 'TZA',
    name: 'Tanzania',
    countryCallingCodes: ['+255'],
  },
  {
    alpha2: 'UA',
    alpha3: 'UKR',
    name: 'Ukraine',
    countryCallingCodes: ['+380'],
  },
  {
    alpha2: 'CZ',
    alpha3: 'CZE',
    name: 'Czech Republic',
    countryCallingCodes: ['+420'],
  },
  {
    alpha2: 'HU',
    alpha3: 'HUN',
    name: 'Hungary',
    countryCallingCodes: ['+36'],
  },
  {
    alpha2: 'RO',
    alpha3: 'ROU',
    name: 'Romania',
    countryCallingCodes: ['+40'],
  },
  {
    alpha2: 'SK',
    alpha3: 'SVK',
    name: 'Slovakia',
    countryCallingCodes: ['+421'],
  },
  {
    alpha2: 'HR',
    alpha3: 'HRV',
    name: 'Croatia',
    countryCallingCodes: ['+385'],
  },
  {
    alpha2: 'RS',
    alpha3: 'SRB',
    name: 'Serbia',
    countryCallingCodes: ['+381'],
  },
  {
    alpha2: 'BG',
    alpha3: 'BGR',
    name: 'Bulgaria',
    countryCallingCodes: ['+359'],
  },
  {
    alpha2: 'SI',
    alpha3: 'SVN',
    name: 'Slovenia',
    countryCallingCodes: ['+386'],
  },
  {
    alpha2: 'LT',
    alpha3: 'LTU',
    name: 'Lithuania',
    countryCallingCodes: ['+370'],
  },
  {
    alpha2: 'LV',
    alpha3: 'LVA',
    name: 'Latvia',
    countryCallingCodes: ['+371'],
  },
  {
    alpha2: 'EE',
    alpha3: 'EST',
    name: 'Estonia',
    countryCallingCodes: ['+372'],
  },
  {
    alpha2: 'BY',
    alpha3: 'BLR',
    name: 'Belarus',
    countryCallingCodes: ['+375'],
  },
  {
    alpha2: 'MD',
    alpha3: 'MDA',
    name: 'Moldova',
    countryCallingCodes: ['+373'],
  },
  {
    alpha2: 'AL',
    alpha3: 'ALB',
    name: 'Albania',
    countryCallingCodes: ['+355'],
  },
  {
    alpha2: 'MK',
    alpha3: 'MKD',
    name: 'North Macedonia',
    countryCallingCodes: ['+389'],
  },
  {
    alpha2: 'ME',
    alpha3: 'MNE',
    name: 'Montenegro',
    countryCallingCodes: ['+382'],
  },
  {
    alpha2: 'BA',
    alpha3: 'BIH',
    name: 'Bosnia and Herzegovina',
    countryCallingCodes: ['+387'],
  },
  {
    alpha2: 'IS',
    alpha3: 'ISL',
    name: 'Iceland',
    countryCallingCodes: ['+354'],
  },
  {
    alpha2: 'LU',
    alpha3: 'LUX',
    name: 'Luxembourg',
    countryCallingCodes: ['+352'],
  },
  {
    alpha2: 'MT',
    alpha3: 'MLT',
    name: 'Malta',
    countryCallingCodes: ['+356'],
  },
  {
    alpha2: 'CY',
    alpha3: 'CYP',
    name: 'Cyprus',
    countryCallingCodes: ['+357'],
  },
  {
    alpha2: 'KZ',
    alpha3: 'KAZ',
    name: 'Kazakhstan',
    countryCallingCodes: ['+7'],
  },
  {
    alpha2: 'UZ',
    alpha3: 'UZB',
    name: 'Uzbekistan',
    countryCallingCodes: ['+998'],
  },
  {
    alpha2: 'KG',
    alpha3: 'KGZ',
    name: 'Kyrgyzstan',
    countryCallingCodes: ['+996'],
  },
  {
    alpha2: 'TJ',
    alpha3: 'TJK',
    name: 'Tajikistan',
    countryCallingCodes: ['+992'],
  },
  {
    alpha2: 'TM',
    alpha3: 'TKM',
    name: 'Turkmenistan',
    countryCallingCodes: ['+993'],
  },
  {
    alpha2: 'MN',
    alpha3: 'MNG',
    name: 'Mongolia',
    countryCallingCodes: ['+976'],
  },
  {
    alpha2: 'BT',
    alpha3: 'BTN',
    name: 'Bhutan',
    countryCallingCodes: ['+975'],
  },
  {
    alpha2: 'NP',
    alpha3: 'NPL',
    name: 'Nepal',
    countryCallingCodes: ['+977'],
  },
  {
    alpha2: 'LK',
    alpha3: 'LKA',
    name: 'Sri Lanka',
    countryCallingCodes: ['+94'],
  },
  {
    alpha2: 'MV',
    alpha3: 'MDV',
    name: 'Maldives',
    countryCallingCodes: ['+960'],
  },
  {
    alpha2: 'BD',
    alpha3: 'BGD',
    name: 'Bangladesh',
    countryCallingCodes: ['+880'],
  },
  {
    alpha2: 'PK',
    alpha3: 'PAK',
    name: 'Pakistan',
    countryCallingCodes: ['+92'],
  },
  {
    alpha2: 'AF',
    alpha3: 'AFG',
    name: 'Afghanistan',
    countryCallingCodes: ['+93'],
  },
  {
    alpha2: 'IR',
    alpha3: 'IRN',
    name: 'Iran',
    countryCallingCodes: ['+98'],
  },
  {
    alpha2: 'IQ',
    alpha3: 'IRQ',
    name: 'Iraq',
    countryCallingCodes: ['+964'],
  },
  {
    alpha2: 'SY',
    alpha3: 'SYR',
    name: 'Syria',
    countryCallingCodes: ['+963'],
  },
  {
    alpha2: 'JO',
    alpha3: 'JOR',
    name: 'Jordan',
    countryCallingCodes: ['+962'],
  },
  {
    alpha2: 'LB',
    alpha3: 'LBN',
    name: 'Lebanon',
    countryCallingCodes: ['+961'],
  },
  {
    alpha2: 'KW',
    alpha3: 'KWT',
    name: 'Kuwait',
    countryCallingCodes: ['+965'],
  },
  {
    alpha2: 'BH',
    alpha3: 'BHR',
    name: 'Bahrain',
    countryCallingCodes: ['+973'],
  },
  {
    alpha2: 'QA',
    alpha3: 'QAT',
    name: 'Qatar',
    countryCallingCodes: ['+974'],
  },
  {
    alpha2: 'OM',
    alpha3: 'OMN',
    name: 'Oman',
    countryCallingCodes: ['+968'],
  },
  {
    alpha2: 'YE',
    alpha3: 'YEM',
    name: 'Yemen',
    countryCallingCodes: ['+967'],
  },
  {
    alpha2: 'PS',
    alpha3: 'PSE',
    name: 'Palestine',
    countryCallingCodes: ['+970'],
  },
  {
    alpha2: 'AZ',
    alpha3: 'AZE',
    name: 'Azerbaijan',
    countryCallingCodes: ['+994'],
  },
  {
    alpha2: 'AM',
    alpha3: 'ARM',
    name: 'Armenia',
    countryCallingCodes: ['+374'],
  },
  {
    alpha2: 'GE',
    alpha3: 'GEO',
    name: 'Georgia',
    countryCallingCodes: ['+995'],
  },
  {
    alpha2: 'CU',
    alpha3: 'CUB',
    name: 'Cuba',
    countryCallingCodes: ['+53'],
  },
  {
    alpha2: 'JM',
    alpha3: 'JAM',
    name: 'Jamaica',
    countryCallingCodes: ['+1876'],
  },
  {
    alpha2: 'HT',
    alpha3: 'HTI',
    name: 'Haiti',
    countryCallingCodes: ['+509'],
  },
  {
    alpha2: 'DO',
    alpha3: 'DOM',
    name: 'Dominican Republic',
    countryCallingCodes: ['+1809', '+1829', '+1849'],
  },
  {
    alpha2: 'PR',
    alpha3: 'PRI',
    name: 'Puerto Rico',
    countryCallingCodes: ['+1787', '+1939'],
  },
  {
    alpha2: 'PA',
    alpha3: 'PAN',
    name: 'Panama',
    countryCallingCodes: ['+507'],
  },
  {
    alpha2: 'CR',
    alpha3: 'CRI',
    name: 'Costa Rica',
    countryCallingCodes: ['+506'],
  },
  {
    alpha2: 'NI',
    alpha3: 'NIC',
    name: 'Nicaragua',
    countryCallingCodes: ['+505'],
  },
  {
    alpha2: 'HN',
    alpha3: 'HND',
    name: 'Honduras',
    countryCallingCodes: ['+504'],
  },
  {
    alpha2: 'SV',
    alpha3: 'SLV',
    name: 'El Salvador',
    countryCallingCodes: ['+503'],
  },
  {
    alpha2: 'GT',
    alpha3: 'GTM',
    name: 'Guatemala',
    countryCallingCodes: ['+502'],
  },
  {
    alpha2: 'BZ',
    alpha3: 'BLZ',
    name: 'Belize',
    countryCallingCodes: ['+501'],
  },
  {
    alpha2: 'BS',
    alpha3: 'BHS',
    name: 'Bahamas',
    countryCallingCodes: ['+1242'],
  },
  {
    alpha2: 'BB',
    alpha3: 'BRB',
    name: 'Barbados',
    countryCallingCodes: ['+1246'],
  },
  {
    alpha2: 'TT',
    alpha3: 'TTO',
    name: 'Trinidad and Tobago',
    countryCallingCodes: ['+1868'],
  },
  {
    alpha2: 'AG',
    alpha3: 'ATG',
    name: 'Antigua and Barbuda',
    countryCallingCodes: ['+1268'],
  },
  {
    alpha2: 'DM',
    alpha3: 'DMA',
    name: 'Dominica',
    countryCallingCodes: ['+1767'],
  },
  {
    alpha2: 'KN',
    alpha3: 'KNA',
    name: 'Saint Kitts and Nevis',
    countryCallingCodes: ['+1869'],
  },
  {
    alpha2: 'LC',
    alpha3: 'LCA',
    name: 'Saint Lucia',
    countryCallingCodes: ['+1758'],
  },
  {
    alpha2: 'VC',
    alpha3: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    countryCallingCodes: ['+1784'],
  },
  {
    alpha2: 'GD',
    alpha3: 'GRD',
    name: 'Grenada',
    countryCallingCodes: ['+1473'],
  },
  {
    alpha2: 'UY',
    alpha3: 'URY',
    name: 'Uruguay',
    countryCallingCodes: ['+598'],
  },
  {
    alpha2: 'PY',
    alpha3: 'PRY',
    name: 'Paraguay',
    countryCallingCodes: ['+595'],
  },
  {
    alpha2: 'BO',
    alpha3: 'BOL',
    name: 'Bolivia',
    countryCallingCodes: ['+591'],
  },
  {
    alpha2: 'EC',
    alpha3: 'ECU',
    name: 'Ecuador',
    countryCallingCodes: ['+593'],
  },
  {
    alpha2: 'GY',
    alpha3: 'GUY',
    name: 'Guyana',
    countryCallingCodes: ['+592'],
  },
  {
    alpha2: 'SR',
    alpha3: 'SUR',
    name: 'Suriname',
    countryCallingCodes: ['+597'],
  },
  {
    alpha2: 'LY',
    alpha3: 'LBY',
    name: 'Libya',
    countryCallingCodes: ['+218'],
  },
  {
    alpha2: 'TN',
    alpha3: 'TUN',
    name: 'Tunisia',
    countryCallingCodes: ['+216'],
  },
  {
    alpha2: 'DZ',
    alpha3: 'DZA',
    name: 'Algeria',
    countryCallingCodes: ['+213'],
  },
  {
    alpha2: 'SD',
    alpha3: 'SDN',
    name: 'Sudan',
    countryCallingCodes: ['+249'],
  },
  {
    alpha2: 'SS',
    alpha3: 'SSD',
    name: 'South Sudan',
    countryCallingCodes: ['+211'],
  },
  {
    alpha2: 'MR',
    alpha3: 'MRT',
    name: 'Mauritania',
    countryCallingCodes: ['+222'],
  },
  {
    alpha2: 'ML',
    alpha3: 'MLI',
    name: 'Mali',
    countryCallingCodes: ['+223'],
  },
  {
    alpha2: 'SN',
    alpha3: 'SEN',
    name: 'Senegal',
    countryCallingCodes: ['+221'],
  },
  {
    alpha2: 'GM',
    alpha3: 'GMB',
    name: 'Gambia',
    countryCallingCodes: ['+220'],
  },
  {
    alpha2: 'GW',
    alpha3: 'GNB',
    name: 'Guinea-Bissau',
    countryCallingCodes: ['+245'],
  },
  {
    alpha2: 'GN',
    alpha3: 'GIN',
    name: 'Guinea',
    countryCallingCodes: ['+224'],
  },
  {
    alpha2: 'SL',
    alpha3: 'SLE',
    name: 'Sierra Leone',
    countryCallingCodes: ['+232'],
  },
  {
    alpha2: 'LR',
    alpha3: 'LBR',
    name: 'Liberia',
    countryCallingCodes: ['+231'],
  },
  {
    alpha2: 'CI',
    alpha3: 'CIV',
    name: "Côte d'Ivoire",
    countryCallingCodes: ['+225'],
  },
  {
    alpha2: 'BF',
    alpha3: 'BFA',
    name: 'Burkina Faso',
    countryCallingCodes: ['+226'],
  },
  {
    alpha2: 'NE',
    alpha3: 'NER',
    name: 'Niger',
    countryCallingCodes: ['+227'],
  },
  {
    alpha2: 'TG',
    alpha3: 'TGO',
    name: 'Togo',
    countryCallingCodes: ['+228'],
  },
  {
    alpha2: 'BJ',
    alpha3: 'BEN',
    name: 'Benin',
    countryCallingCodes: ['+229'],
  },
  {
    alpha2: 'CM',
    alpha3: 'CMR',
    name: 'Cameroon',
    countryCallingCodes: ['+237'],
  },
  {
    alpha2: 'TD',
    alpha3: 'TCD',
    name: 'Chad',
    countryCallingCodes: ['+235'],
  },
  {
    alpha2: 'CF',
    alpha3: 'CAF',
    name: 'Central African Republic',
    countryCallingCodes: ['+236'],
  },
  {
    alpha2: 'GA',
    alpha3: 'GAB',
    name: 'Gabon',
    countryCallingCodes: ['+241'],
  },
  {
    alpha2: 'CG',
    alpha3: 'COG',
    name: 'Republic of the Congo',
    countryCallingCodes: ['+242'],
  },
  {
    alpha2: 'CD',
    alpha3: 'COD',
    name: 'Democratic Republic of the Congo',
    countryCallingCodes: ['+243'],
  },
  {
    alpha2: 'AO',
    alpha3: 'AGO',
    name: 'Angola',
    countryCallingCodes: ['+244'],
  },
  {
    alpha2: 'NA',
    alpha3: 'NAM',
    name: 'Namibia',
    countryCallingCodes: ['+264'],
  },
  {
    alpha2: 'BW',
    alpha3: 'BWA',
    name: 'Botswana',
    countryCallingCodes: ['+267'],
  },
  {
    alpha2: 'ZW',
    alpha3: 'ZWE',
    name: 'Zimbabwe',
    countryCallingCodes: ['+263'],
  },
  {
    alpha2: 'MZ',
    alpha3: 'MOZ',
    name: 'Mozambique',
    countryCallingCodes: ['+258'],
  },
  {
    alpha2: 'ZM',
    alpha3: 'ZMB',
    name: 'Zambia',
    countryCallingCodes: ['+260'],
  },
  {
    alpha2: 'MG',
    alpha3: 'MDG',
    name: 'Madagascar',
    countryCallingCodes: ['+261'],
  },
  {
    alpha2: 'MU',
    alpha3: 'MUS',
    name: 'Mauritius',
    countryCallingCodes: ['+230'],
  },
  {
    alpha2: 'SC',
    alpha3: 'SYC',
    name: 'Seychelles',
    countryCallingCodes: ['+248'],
  },
  {
    alpha2: 'KM',
    alpha3: 'COM',
    name: 'Comoros',
    countryCallingCodes: ['+269'],
  },
  {
    alpha2: 'ET',
    alpha3: 'ETH',
    name: 'Ethiopia',
    countryCallingCodes: ['+251'],
  },
  {
    alpha2: 'ER',
    alpha3: 'ERI',
    name: 'Eritrea',
    countryCallingCodes: ['+291'],
  },
  {
    alpha2: 'DJ',
    alpha3: 'DJI',
    name: 'Djibouti',
    countryCallingCodes: ['+253'],
  },
  {
    alpha2: 'SO',
    alpha3: 'SOM',
    name: 'Somalia',
    countryCallingCodes: ['+252'],
  },
  {
    alpha2: 'UG',
    alpha3: 'UGA',
    name: 'Uganda',
    countryCallingCodes: ['+256'],
  },
  {
    alpha2: 'RW',
    alpha3: 'RWA',
    name: 'Rwanda',
    countryCallingCodes: ['+250'],
  },
  {
    alpha2: 'BI',
    alpha3: 'BDI',
    name: 'Burundi',
    countryCallingCodes: ['+257'],
  },
  {
    alpha2: 'MM',
    alpha3: 'MMR',
    name: 'Myanmar',
    countryCallingCodes: ['+95'],
  },
  {
    alpha2: 'LA',
    alpha3: 'LAO',
    name: 'Laos',
    countryCallingCodes: ['+856'],
  },
  {
    alpha2: 'KH',
    alpha3: 'KHM',
    name: 'Cambodia',
    countryCallingCodes: ['+855'],
  },
]
