export const LOGIN_STEP = 0
export const SIGN_UP_STEP = 4
export const SIGN_UP_PERSONAL_INFO_STEP = SIGN_UP_STEP + 1
export const SIGN_UP_VERIFICATION_STEP = SIGN_UP_STEP + 2
export const FORGOT_PASSWORD_STEP = LOGIN_STEP + 1
export const RESET_PASSWORD_VERIFICATION_STEP = LOGIN_STEP + 2
export const RESET_PASSWORD_STEP = LOGIN_STEP + 3
