name: Storefront 1000029513
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache bun modules
        id: cache-bun
        uses: actions/cache@v4
        env:
          cache-name: cache-bun-modules
        with:
          path: ~/.bun
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build and Publish to Oxygen
        run: bunx shopify hydrogen deploy
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000029513 }}
